[[language]]
name = "r"
auto-format = true
file-types = ["R", "Rmd"]

[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py", "ipynb"]
roots = []
comment-token = "#"
language-servers = ["jedi", "pylsp", "ruff"]
auto-format = true

[language.formatter]
command = "black"
args = ["--fast", "-"]
stdin = true

[[language]]
name = "latex"
file-types = ["tex", "sty", "cls", "ltx"]
language-servers = ["texlab"]
auto-format = true

[language.formatter]
command = "latexindent"
args = ["-w"]

